name: saidi_s_application3
description: A new Flutter project.
version: 1.1.6+17
environment: 
  sdk: '>=2.19.6 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  fluttertoast: ^8.2.4
  multi_select_flutter: ^4.1.3
  mobile_scanner: ^3.2.0
  platform_device_id: ^1.0.1
  package_info_plus: ^4.0.2
  flutter_otp_text_field: ^1.1.1
  flutter_holo_date_picker: ^1.1.3
  geolocator: ^11.0.0
  image_picker: ^1.1.1
  maps_toolkit: ^3.0.0
  google_mlkit_face_detection: ^0.11.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
